1)Load the Iris dataset and explore its structure using functions like df.head().

2)Extract features (X) and the target variable (y) from the dataset.

3)Encode the target variable (y) .

4)Normalize the feature set (X).

5)Split the dataset into training and testing sets .

6)Implement and train a LinearRegression model, then use it to predict on the test data.

7)Implement and train a LogisticRegression model, then use it to predict on the test data.

8)Implement and train an SGDClassifier with logistic loss, then use it to predict on the test data.

9)Evaluate the models’ performance by calculating accuracy or other metrics.

10)Save and compare the actual and predicted labels from all models in a DataFrame.

In [12]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression, LogisticRegression, SGDClassifier
from sklearn.preprocessing import StandardScaler, LabelEncoder

1. Load the Iris Dataset

In [29]:
iris = load_iris()
df = pd.DataFrame(data=iris.data , columns=iris.feature_names)
print(df.head())
print(iris.target)

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


2. Select Features and Target

In [28]:
x = iris.data
y = iris.target
print(x)
print(y)


[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

3. Encode the Target Variable

In [ ]:
y_names = iris.target_names
print(y_names)
y_all = [y_names[names] for names in y]
label_encoder = LabelEncoder()
y_encoded = label_encoder.fit_transform(y_all)
print(y_encoded)


['setosa' 'versicolor' 'virginica']
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


4. Normalize Features

In [35]:
scaler = StandardScaler()
X_scaled = scaler.fit_transform(x)
print(X_scaled)


[[-9.00681170e-01  1.01900435e+00 -1.34022653e+00 -1.31544430e+00]
 [-1.14301691e+00 -1.31979479e-01 -1.34022653e+00 -1.31544430e+00]
 [-1.38535265e+00  3.28414053e-01 -1.39706395e+00 -1.31544430e+00]
 [-1.50652052e+00  9.82172869e-02 -1.28338910e+00 -1.31544430e+00]
 [-1.02184904e+00  1.24920112e+00 -1.34022653e+00 -1.31544430e+00]
 [-5.37177559e-01  1.93979142e+00 -1.16971425e+00 -1.05217993e+00]
 [-1.50652052e+00  7.88807586e-01 -1.34022653e+00 -1.18381211e+00]
 [-1.02184904e+00  7.88807586e-01 -1.28338910e+00 -1.31544430e+00]
 [-1.74885626e+00 -3.62176246e-01 -1.34022653e+00 -1.31544430e+00]
 [-1.14301691e+00  9.82172869e-02 -1.28338910e+00 -1.44707648e+00]
 [-5.37177559e-01  1.47939788e+00 -1.28338910e+00 -1.31544430e+00]
 [-1.26418478e+00  7.88807586e-01 -1.22655167e+00 -1.31544430e+00]
 [-1.26418478e+00 -1.31979479e-01 -1.34022653e+00 -1.44707648e+00]
 [-1.87002413e+00 -1.31979479e-01 -1.51073881e+00 -1.44707648e+00]
 [-5.25060772e-02  2.16998818e+00 -1.45390138e+00 -1.31544430e

5. Split the Dataset

In [36]:
x_train,x_test,y_train,y_test= train_test_split(X_scaled,y_encoded,train_size=0.8,random_state=42)

6. Implement Linear Regression

In [ ]:
linear_model = LinearRegression()
linear_model.fit(x_train,y_train)
y_pred_linear = linear_model.predict(x_test)
print(y_pred_linear)

[ 1.23071715 -0.04010441  2.21970287  1.34966889  1.28429336  0.02248402
  1.05726124  1.82403704  1.36824643  1.06766437  1.70031437 -0.07357413
 -0.15562919 -0.06569402 -0.02128628  1.39659966  2.00022876  1.04812731
  1.28102792  1.97283506  0.03184612  1.59830192  0.09450931  1.91807547
  1.83296682  1.87877315  1.78781234  2.03362373  0.03594506  0.02619043]


7. Implement Logistic Regression

In [57]:
logistic_model = LogisticRegression(max_iter=200)
logistic_model.fit(x_train,y_train)
y_pred_logistic = logistic_model.predict(x_test)
print(y_pred_logistic)

[1 0 2 1 1 0 1 2 1 1 2 0 0 0 0 1 2 1 1 2 0 2 0 2 2 2 2 2 0 0]


8. Implement SGD (Stochastic Gradient Descent)

In [60]:
sgd= SGDClassifier(loss='log_loss', max_iter=200, tol=1e-3, random_state=42)
sgd.fit(x_train,y_train)
y_pred_sgd = sgd.predict(x_test)
print(y_pred_sgd)

[1 0 2 1 1 0 0 2 1 1 2 0 0 0 0 1 2 1 1 2 0 2 0 2 2 2 2 2 0 0]


9. Evaluate the Models

In [73]:
from sklearn.metrics import accuracy_score
y_pred_linear_round = np.round(y_pred_linear)
acc_linear_regression= accuracy_score(y_test , y_pred_linear_round)
acc_logistic_regression=accuracy_score(y_test,y_pred_logistic)
acc_sgd=accuracy_score(y_test,y_pred_sgd)
print("Linear Regression Accuracy:",acc_linear_regression)
print("Logistic Regression Accuracy:",acc_logistic_regression)
print("SGD Accuracy:" ,acc_sgd)

Linear Regression Accuracy: 1.0
Logistic Regression Accuracy: 1.0
SGD Accuracy: 0.9666666666666667


In [74]:
from sklearn.model_selection import cross_val_score
cv_scores_linear = cross_val_score(linear_model, X_scaled, y_encoded, cv=5)
cv_scores_logistic = cross_val_score(logistic_model, X_scaled, y_encoded, cv=5)
cv_scores_sgd = cross_val_score(sgd, X_scaled, y_encoded, cv=5)
print("Linear Regression Accuracy:", cv_scores_linear.mean())
print("Logistic Regression Accuracy:", cv_scores_logistic.mean())
print("SGD Accuracy:", cv_scores_sgd.mean())


Linear Regression Accuracy: 0.3225607248900084
Logistic Regression Accuracy: 0.9600000000000002
SGD Accuracy: 0.9199999999999999


10. Save Predictions

In [69]:
y_pred_linear_round = np.round(y_pred_linear)
submission = pd.DataFrame({
    'Actual': y_test,
    'Predicted_Linear': y_pred_linear_round,
    'Predicted_Logistic': y_pred_logistic,
    'Predicted_SGD': y_pred_sgd
})
print(submission.head())

   Actual  Predicted_Linear  Predicted_Logistic  Predicted_SGD
0       1               1.0                   1              1
1       0              -0.0                   0              0
2       2               2.0                   2              2
3       1               1.0                   1              1
4       1               1.0                   1              1
